version: 2
updates:
  # Enable version updates for Python
  - package-ecosystem: "pip"
    # Look for requirements.txt in the root directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Labels on pull requests for pip dependencies
    labels:
      - "pip dependencies"

  # Enable version updates for Docker - main Dockerfile
  - package-ecosystem: "docker"
    # Look for the main Dockerfile in the root directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Labels on pull requests for Docker dependencies
    labels:
      - "docker dependencies"
      - "main dockerfile"

  # Enable version updates for Docker - webui Dockerfile
  - package-ecosystem: "docker"
    # Using a virtual directory to avoid conflicts with the main Dockerfile
    directory: "/webui"
    schedule:
      interval: "weekly"
    # Specify the custom Dockerfile name with path from the virtual directory
    dockerfile: "../Dockerfile.webui"
    labels:
      - "docker dependencies"
      - "webui dockerfile"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Look for GitHub Actions workflows in the .github/workflows directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Labels on pull requests for GitHub Actions
    labels:
      - "github-actions dependencies"
