version: 2
updates:
  # Enable version updates for Python
  - package-ecosystem: "pip"
    # Look for requirements.txt in the root directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Labels on pull requests for pip dependencies
    labels:
      - "pip dependencies"

  # Enable version updates for Docker - main Dockerfile
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
    labels:
      - "docker dependencies"
      - "main dockerfile"

  # Enable version updates for Docker - webui Dockerfile
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "docker dependencies"
      - "webui dockerfile"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "github-actions dependencies"
