services:
    kokoro-tts:
      image: aaronbolton78/kokoro-container:latest
      container_name: kokoro-tts
      ports:
        - "5001:5001"
      volumes:
        - ./kokoro-tts/output:/app/output
        - ./kokoro-tts/input:/app/input
        - ./kokoro-tts/huggingface:/root/.cache/huggingface
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: all
                capabilities: [gpu]