name: Docker Build and Push

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    paths:
          - '**.py'
          - 'static/**'
          - 'templates/**'
          - 'Dockerfile'
          - 'Dockerfile.webui'
          - 'requirements.txt'
          
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Docker tags based on branch
        id: tags
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "GHCR_TAG=ghcr.io/${{ github.repository }}:latest" >> $GITHUB_OUTPUT
            echo "DOCKER_TAG=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest" >> $GITHUB_OUTPUT
          elif [[ ${{ github.ref }} == 'refs/heads/dev' ]]; then
            echo "GHCR_TAG=ghcr.io/${{ github.repository }}:dev" >> $GITHUB_OUTPUT
            echo "DOCKER_TAG=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:dev" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.webui
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.tags.outputs.GHCR_TAG }}
            ${{ steps.tags.outputs.DOCKER_TAG }}